Repository AY2425S2-CS2113-F11-4/tp, pull requests merged in 2025-03, with the labels that each got.

#16 View answer
  src/main/java/command/CommandViewAnswer.java
  src/main/java/command/CommandViewQuestion.java
  src/main/java/constants/CommandConstants.java
  src/main/java/constants/SuccessMessages.java
  src/main/java/flashcard/types/FlashcardList.java
  src/main/java/flashcli/FlashCLI.java
  src/main/java/parser/Parser.java
  src/test/java/flashcard/types/FlashcardListTest.java
Labels: priority.High

#17 List flashcard
  src/main/java/command/CommandCreate.java
  src/main/java/command/CommandEdit.java
  src/main/java/command/CommandListQuestion.java
  src/main/java/command/CommandViewAnswer.java
  src/main/java/constants/CommandConstants.java
  src/main/java/constants/ErrorMessages.java
  src/main/java/constants/SuccessMessages.java
  src/main/java/exceptions/EmptyListException.java
  src/main/java/exceptions/FlashCLIillegalArgumentException.java
  src/main/java/exceptions/IllegalArgumentException.java
  src/main/java/flashcard/types/FlashcardList.java
  src/main/java/flashcli/FlashCLI.java
  src/main/java/parser/Parser.java
  src/test/java/flashcard/types/FlashcardListTest.java
Labels: priority.High

#35 Deck feature
  build.gradle
  src/main/java/command/CommandCreate.java
  src/main/java/command/CommandCreateDeck.java
  src/main/java/command/CommandDelete.java
  src/main/java/command/CommandEdit.java
  src/main/java/command/CommandListQuestion.java
  src/main/java/command/CommandRenameDeck.java
  src/main/java/command/CommandSwitchDeck.java
  src/main/java/command/CommandViewAnswer.java
  src/main/java/command/CommandViewDecks.java
  src/main/java/command/CommandViewQuestion.java
  src/main/java/constants/CommandConstants.java
  src/main/java/constants/ErrorMessages.java
  src/main/java/constants/SuccessMessages.java
  src/main/java/deck/Deck.java
  src/main/java/deck/DeckManager.java
  src/main/java/deck/Flashcard.java
  src/main/java/exceptions/FlashCLIArgumentException.java
  src/main/java/exceptions/FlashCLIillegalArgumentException.java
  src/main/java/flashcli/FlashCLI.java
  src/main/java/parser/Parser.java
  src/test/java/deck/DeckTest.java
  src/test/java/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium

#36 Decks tests
  src/main/java/command/CommandCreateDeck.java
  src/main/java/command/CommandRenameDeck.java
  src/main/java/command/CommandSwitchDeck.java
  src/main/java/command/CommandViewDecks.java
  src/main/java/deck/Deck.java
  src/main/java/deck/DeckManager.java
  src/main/java/parser/Parser.java
  src/test/java/deck/DeckManagerTest.java
  src/test/java/deck/DeckTest.java
Labels: type.Task

#51 Deck feature addons
  src/main/java/command/CommandDeleteDeck.java
  src/main/java/constants/CommandConstants.java
  src/main/java/constants/ConfirmationMessages.java
  src/main/java/constants/ErrorMessages.java
  src/main/java/constants/SuccessMessages.java
  src/main/java/constants/UserGuideMessages.java
  src/main/java/deck/Deck.java
  src/main/java/deck/DeckManager.java
  src/main/java/flashcli/FlashCLI.java
  src/main/java/parser/Parser.java
  src/test/java/deck/DeckManagerTest.java
Labels: priority.Medium
